In [1]:
import pandas as pd

In [2]:
df_477 = pd.read_csv("/Users/katherineaquino/Downloads/477_complete_1125.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df_477.head()

,census_tract_full,affgeoid_code,state_code,county_code,tract_ce,LEAID,name_district,sp_frn,name,hocoA,technology,committed
0,1001020100,1400000US01001020100,1,1,20100,100240,Autauga County School District,12369286,"HNS License Sub, LLC","Hughes Network Systems, LLC",Satellite,False
1,1001020100,1400000US01001020100,1,1,20100,100240,Autauga County School District,1857952,"BellSouth Telecommunications, Inc.",AT&T Inc.,DSL,True
2,1001020100,1400000US01001020100,1,1,20100,100240,Autauga County School District,18756155,"VSAT Systems, LLC","VSAT Systems, LLC",Satellite,False
3,1001020100,1400000US01001020100,1,1,20100,100240,Autauga County School District,25646373,"Charter Communications, Inc.",Charter Communications,Cable,True
4,1001020100,1400000US01001020100,1,1,20100,100240,Autauga County School District,3766144,"Knology of Alabama, Inc.","WideOpenWest Finance, LLC",Cable,True

In [48]:
df_477.drop('affgeoid_code', axis=1, inplace=True)

In [49]:
df_477.shape

(937382, 11)

In [18]:
df_pop = pd.read_csv("/Users/katherineaquino/Downloads/Population by Census Tract - population.csv")

In [19]:
df_pop.head()

,census_tract_full,state_code,county_code,tract_only,population_tract,population_state
0,1001020100,1,1,20100,1912,4779736
1,1001020200,1,1,20200,2170,4779736
2,1001020300,1,1,20300,3373,4779736
3,1001020400,1,1,20400,4386,4779736
4,1001020500,1,1,20500,10766,4779736

In [20]:
df_pop.shape

(74002, 6)

### Merge df's for population

In [50]:
df = pd.merge(df_477, 
              df_pop[['census_tract_full', 'tract_only', 'population_tract', 'population_state']], 
              on='census_tract_full', how='left')

In [51]:
df.shape

(937382, 14)

In [52]:
df.head()

,census_tract_full,state_code,county_code,tract_ce,LEAID,name_district,sp_frn,name,hocoA,technology,committed,tract_only,population_tract,population_state
0,1001020100,1,1,20100,100240,Autauga County School District,12369286,"HNS License Sub, LLC","Hughes Network Systems, LLC",Satellite,False,20100.0,1912.0,4779736.0
1,1001020100,1,1,20100,100240,Autauga County School District,1857952,"BellSouth Telecommunications, Inc.",AT&T Inc.,DSL,True,20100.0,1912.0,4779736.0
2,1001020100,1,1,20100,100240,Autauga County School District,18756155,"VSAT Systems, LLC","VSAT Systems, LLC",Satellite,False,20100.0,1912.0,4779736.0
3,1001020100,1,1,20100,100240,Autauga County School District,25646373,"Charter Communications, Inc.",Charter Communications,Cable,True,20100.0,1912.0,4779736.0
4,1001020100,1,1,20100,100240,Autauga County School District,3766144,"Knology of Alabama, Inc.","WideOpenWest Finance, LLC",Cable,True,20100.0,1912.0,4779736.0

In [53]:
df[df.census_tract_full == 1001020100]

,census_tract_full,state_code,county_code,tract_ce,LEAID,name_district,sp_frn,name,hocoA,technology,committed,tract_only,population_tract,population_state
0,1001020100,1,1,20100,100240,Autauga County School District,12369286,"HNS License Sub, LLC","Hughes Network Systems, LLC",Satellite,False,20100.0,1912.0,4779736.0
1,1001020100,1,1,20100,100240,Autauga County School District,1857952,"BellSouth Telecommunications, Inc.",AT&T Inc.,DSL,True,20100.0,1912.0,4779736.0
2,1001020100,1,1,20100,100240,Autauga County School District,18756155,"VSAT Systems, LLC","VSAT Systems, LLC",Satellite,False,20100.0,1912.0,4779736.0
3,1001020100,1,1,20100,100240,Autauga County School District,25646373,"Charter Communications, Inc.",Charter Communications,Cable,True,20100.0,1912.0,4779736.0
4,1001020100,1,1,20100,100240,Autauga County School District,3766144,"Knology of Alabama, Inc.","WideOpenWest Finance, LLC",Cable,True,20100.0,1912.0,4779736.0
5,1001020100,1,1,20100,100240,Autauga County School District,3766144,"Knology of Alabama, Inc.","WideOpenWest Finance, LLC",Fiber,True,20100.0,1912.0,4779736.0
6,1001020100,1,1,20100,100240,Autauga County School District,4963088,"ViaSat, Inc.","ViaSat, Inc.",Satellite,False,20100.0,1912.0,4779736.0

In [54]:
# df["Order_Total"] = df.groupby('order')["ext price"].transform('sum')

In [55]:
df[['population_tract', 'population_state']] = df[['population_tract', 'population_state']].astype(float)

In [56]:
# state committment
df["pop_state_committed"] = df.groupby(['state_code', 'committed'])['population_tract'].transform('sum')

In [57]:
# district committment
df["pop_district_committed"] = df.groupby(['LEAID', 'committed'])['population_tract'].transform('sum')

In [58]:
# state tech committment
df['pop_state_tech_committed'] = df.groupby(['state_code', 'technology','committed'])['population_tract'].transform('sum')

In [59]:
# district tech committment
df['pop_district_tech_committed'] = df.groupby(['LEAID', 'technology','committed'])['population_tract'].transform('sum')

In [60]:
subset = ['census_tract_full','state_code', 'LEAID', 'technology','committed', 'pop_state_tech_committed', 'pop_district_tech_committed']
df[subset].head(50)

,census_tract_full,state_code,LEAID,technology,committed,pop_state_tech_committed,pop_district_tech_committed
0,1001020100,1,100240,Satellite,False,22954455.0,163713.0
1,1001020100,1,100240,DSL,True,7286010.0,54571.0
2,1001020100,1,100240,Satellite,False,22954455.0,163713.0
3,1001020100,1,100240,Cable,True,10733228.0,94359.0
4,1001020100,1,100240,Cable,True,10733228.0,94359.0
5,1001020100,1,100240,Fiber,True,6574356.0,79198.0
6,1001020100,1,100240,Satellite,False,22954455.0,163713.0
7,1001020200,1,100240,Satellite,False,22954455.0,163713.0
8,1001020200,1,100240,DSL,True,7286010.0,54571.0
9,1001020200,1,100240,Satellite,False,22954455.0,163713.0
10,1001020200,1,100240,Cable,True,10733228.0,94359.0
11,1001020200,1,100240,Cable,True,10733228.0,94359.0
12,1001020200,1,100240,Fiber,True,6574356.0,79198.0
13,1001020200,1,100240,Satellite,False,22954455.0,163713.0
14,1001020300,1,100240,Satellite,False,22954455.0,163713.0
15,1001020300,1,100240,DSL,True,7286010.0,54571.0
16,1001020300,1,100240,Satellite,False,22954455.0,163713.0
17,1001020300,1,100240,Cable,True,10733228.0,94359.0
18,1001020300,1,100240,Cable,True,10733228.0,94359.0
19,1001020300,1,100240,Fiber,True,6574356.0,79198.0
20,1001020300,1,100240,Satellite,False,22954455.0,163713.0
21,1001020400,1,100240,Satellite,False,22954455.0,163713.0
22,1001020400,1,100240,DSL,True,7286010.0,54571.0
23,1001020400,1,100240,Satellite,False,22954455.0,163713.0
24,1001020400,1,100240,Cable,True,10733228.0,94359.0
25,1001020400,1,100240,Cable,True,10733228.0,94359.0
26,1001020400,1,100240,Fiber,True,6574356.0,79198.0
27,1001020400,1,100240,Satellite,False,22954455.0,163713.0
28,1001020500,1,100240,Satellite,False,22954455.0,163713.0
29,1001020500,1,100240,DSL,True,7286010.0,54571.0
30,1001020500,1,100240,Fiber,True,6574356.0,79198.0
31,1001020500,1,100240,Satellite,False,22954455.0,163713.0
32,1001020500,1,100240,Cable,True,10733228.0,94359.0
33,1001020500,1,100240,Cable,True,10733228.0,94359.0
34,1001020500,1,100240,Fiber,True,6574356.0,79198.0
35,1001020500,1,100240,Satellite,False,22954455.0,163713.0
36,1001020600,1,100240,Satellite,False,22954455.0,163713.0
37,1001020600,1,100240,DSL,True,7286010.0,54571.0
38,1001020600,1,100240,Fiber,True,6574356.0,79198.0
39,1001020600,1,100240,Satellite,False,22954455.0,163713.0
40,1001020600,1,100240,Cable,True,10733228.0,94359.0
41,1001020600,1,100240,Cable,True,10733228.0,94359.0
42,1001020600,1,100240,Fiber,True,6574356.0,79198.0
43,1001020600,1,100240,Satellite,False,22954455.0,163713.0
44,1001020700,1,100240,Satellite,False,22954455.0,163713.0
45,1001020700,1,100240,DSL,True,7286010.0,54571.0
46,1001020700,1,100240,Fiber,True,6574356.0,79198.0
47,1001020700,1,100240,Satellite,False,22954455.0,163713.0
48,1001020700,1,100240,Cable,True,10733228.0,94359.0
49,1001020700,1,100240,Cable,True,10733228.0,94359.0

In [61]:
# save as csv
df.to_csv("477_complete_with_population_113020.csv", index=False)