In [1]:
import pandas as pd

In [3]:
df_ar = pd.read_csv('/Users/katherineaquino/Downloads/AR-Fixed-Dec2019-v1.csv')

In [5]:
df_ar.head(10)

,LogRecNo,Provider_Id,FRN,ProviderName,DBAName,HoldingCompanyName,HocoNum,HocoFinal,StateAbbr,BlockCode,TechCode,Consumer,MaxAdDown,MaxAdUp,Business
0,26175,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014802001218,50,0,0.0,0.0,1
1,26176,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014802002115,50,0,0.0,0.0,1
2,26177,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014802002120,50,0,0.0,0.0,1
3,26178,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014802002159,50,0,0.0,0.0,1
4,26179,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014803001020,50,0,0.0,0.0,1
5,26180,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014803001021,50,0,0.0,0.0,1
6,26181,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014803001054,50,0,0.0,0.0,1
7,26182,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014803001055,50,0,0.0,0.0,1
8,26183,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014803001065,50,0,0.0,0.0,1
9,26184,53788,3723822,"Level 3 Communications, LLC",CenturyLink,"CenturyLink, Inc.",130228,"CenturyLink, Inc.",AR,50014803001074,50,0,0.0,0.0,1